# Generated by Django 3.1.3 on 2023-05-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
