# Generated by Django 3.1.3 on 2023-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
