# Generated by Django 3.1.3 on 2023-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20230522_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
